version: '3'
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    # volumes:
    #   - ./data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000/
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=true
      - GF_ALERTING_ERROR_OR_TIMEOUT=keep_state
    restart: always
    depends_on:
      - mysqlsrv
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"